
CREATE TABLE `adminemails` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` enum("errors", "comments"),
  `firstName` varchar(50) NOT NULL,
  `lastname` varchar(50) NOT NULL,
  `email` varchar(150) NOT NULL,
  `createdAt` DATETIME DEFAULT NULL,
  `createdBy` MEDIUMINT(8) UNSIGNED DEFAULT NULL,
  `updatedAt` DATETIME DEFAULT NULL,
  `updatedBy` MEDIUMINT(8) UNSIGNED DEFAULT NULL,
  `deletedAt` DATETIME DEFAULT NULL,
  `deletedBy` MEDIUMINT(8) UNSIGNED DEFAULT NULL,
  `timestampAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='site emails';
