# DROP TABLE IF EXISTS cvazquezblog.`entrypictures`;
CREATE TABLE IF NOT EXISTS cvazquezblog.`entrypictures` (
	`id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`entryId` MEDIUMINT UNSIGNED NOT NULL,
	`title` VARCHAR(250) NOT NULL,
	`description` TEXT NULL,
	`link100x75` VARCHAR(100) NOT NULL DEFAULT '',
	`link640x480` VARCHAR(100) NOT NULL DEFAULT '',
	`sequence` TINYINT UNSIGNED NOT NULL DEFAULT '0',
	`extension` VARCHAR(4) NOT NULL,

	`takenAt` DATETIME NULL DEFAULT NULL,

	`createdAt` DATETIME NULL DEFAULT NULL,
	`createdBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`updatedAt` DATETIME NULL DEFAULT NULL,
	`updatedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`deletedAt` DATETIME NULL DEFAULT NULL,
	`deletedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`timestampAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

) COMMENT = "Pictures associated with an entry"
  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

/*
	#/images/Cañon-Del-Colca.jpg
	ReWriteRule ^/images/([a-z0-9\-_]+)\.jpg /blog/PictureRedirect/$1 [L,NC]
*/