CREATE TABLE IF NOT EXISTS cvazquezblog.`entrydrafts` (
	`id` MEDIUMINT(9) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`entryId` MEDIUMINT UNSIGNED NULL DEFAULT NULL,

	`content` TEXT NOT NULL,

	`createdAt` DATETIME NULL DEFAULT NULL,
	`createdBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`updatedAt` DATETIME NULL DEFAULT NULL,
	`updatedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`deletedAt` DATETIME NULL DEFAULT NULL,
	`deletedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`timestampAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  	FOREIGN KEY (entryId) REFERENCES entries(id)
) COMMENT = "Saves Blog entries as a draft"
  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;



GRANT SELECT, UPDATE, INSERT ON `cvazquezblog`.`entrydrafts` TO railo@localhost;