-- DROP TABLE IF EXISTS flickroauth;

create table flickroauth
(
	`id` MEDIUMINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`userNSid` VARCHAR(50) NOT NULL,
	`fullName` VARCHAR(50) NOT NULL,
	`userName` VARCHAR(50) NOT NULL,
	`oauthToken` VARCHAR(50) NOT NULL,
	`oauthTokenSecret` VARCHAR(20) NOT NULL,

	`createdAt` DATETIME NULL DEFAULT now(),
	`createdBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`updatedAt` DATETIME NULL DEFAULT NULL,
	`updatedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`deletedAt` DATETIME NULL DEFAULT NULL,
	`deletedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`timestampAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)	comment = "FLickr oAuth Access Tokens for API access"
	ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;