#DROP TABLE IF EXISTS flickrsetphotos;

#/images/Cañon-Del-Colca.jpg
#ReWriteRule ^/images/([a-z0-9\-_]+)\.jpg /blog/PictureRedirect/$1 [L,NC]

CREATE TABLE flickrsetphotos
(
	`id` BIGINT UNSIGNED NOT NULL PRIMARY KEY,
	`flickrSetId` BIGINT UNSIGNED NOT NULL,
	`orderId` SMALLINT UNSIGNED NULL DEFAULT NULL,

	`title` VARCHAR(255) NOT NULL DEFAULT '',
	`description` TEXT NULL DEFAULT NULL,

	`squareURL` VARCHAR(100) NOT NULL DEFAULT '',
	`squareWidth` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	`squareHeight` SMALLINT UNSIGNED NOT NULL DEFAULT 0,

	`smallURL` VARCHAR(100) NOT NULL DEFAULT '',
	`smallWidth` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	`smallHeight` SMALLINT UNSIGNED NOT NULL DEFAULT 0,

	`mediumURL` VARCHAR(100) NOT NULL DEFAULT '',
	`mediumWidth` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
	`mediumHeight` SMALLINT UNSIGNED NOT NULL DEFAULT 0,

	`largeURL` VARCHAR(100) NULL DEFAULT NULL,
	`largeWidth` SMALLINT UNSIGNED NULL DEFAULT NULL,
	`largeHeight` SMALLINT UNSIGNED NULL DEFAULT NULL,

	`takenAt` DATETIME NULL DEFAULT NULL,

	`createdAt` DATETIME NULL DEFAULT NULL,
	`createdBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`updatedAt` DATETIME NULL DEFAULT NULL,
	`updatedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`deletedAt` DATETIME NULL DEFAULT NULL,
	`deletedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`timestampAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (flickrSetId) REFERENCES flickrsets(id)

) COMMENT = "A cache of flickrSetId images of a set"
  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;