#SET FOREIGN_KEY_CHECKS = 0;

#DROP TABLE IF EXISTS flickrcollections;
#TRUNCATE TABLE flickrcollections;

CREATE TABLE flickrcollections
(
	id VARCHAR(50) NOT NULL DEFAULT '' PRIMARY KEY,

	`createdAt` DATETIME NULL DEFAULT NULL,
	`createdBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`updatedAt` DATETIME NULL DEFAULT NULL,
	`updatedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`deletedAt` DATETIME NULL DEFAULT NULL,
	`deletedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`timestampAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

) COMMENT = "Flickr Collections for this Blog"
  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;