# DROP TABLE IF EXISTS cvazquezblog.`pictureurls`;

CREATE TABLE IF NOT EXISTS cvazquezblog.`pictureurls` (
	`entryPictureId` MEDIUMINT UNSIGNED NOT NULL,
	`titleURL` VARCHAR(250) NOT NULL DEFAULT '',
	`isActive` TINYINT(1) NOT NULL DEFAULT 0,

	`createdAt` DATETIME NULL DEFAULT NULL,
	`createdBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`updatedAt` DATETIME NULL DEFAULT NULL,
	`updatedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`deletedAt` DATETIME NULL DEFAULT NULL,
	`deletedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`timestampAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	PRIMARY KEY (entryPictureId, titleURL),

	FOREIGN KEY (entryPictureId) REFERENCES entrypictures(id)

) COMMENT = "Masked URLs for Pictures"
  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;


  ALTER TABLE pictureurls ADD	FOREIGN KEY (entryPictureId) REFERENCES entrypictures(id);