#DROP TABLE IF EXISTS cvazquezblog.`seriesentries`;

CREATE TABLE IF NOT EXISTS cvazquezblog.`seriesentries` (
	`seriesId` MEDIUMINT(9) UNSIGNED NOT NULL,
	`entryId` MEDIUMINT(9) UNSIGNED NOT NULL,
	`sequence` TINYINT UNSIGNED NULL DEFAULT NULL,

	PRIMARY KEY (seriesId, entryId, sequence),

	`createdAt` DATETIME NULL DEFAULT NULL,
	`createdBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`updatedAt` DATETIME NULL DEFAULT NULL,
	`updatedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`deletedAt` DATETIME NULL DEFAULT NULL,
	`deletedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`timestampAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	FOREIGN KEY (seriesId) REFERENCES series(id),
	FOREIGN KEY (entryId) REFERENCES entries(id)

) COMMENT = "Map entries to a series of related entries"
  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;


DROP TRIGGER IF EXISTS seriesentries_bi;

DELIMITER |
CREATE
    DEFINER = blog_trig_user@localhost
    TRIGGER seriesentries_bi BEFORE INSERT
    ON seriesentries FOR EACH ROW

	BEGIN

	IF sequence = 0 THEN
		SET NEW.sequence = NULL;
	END IF;

	END;
|
DELIMITER ;