
# DROP TABLE IF EXISTS cvazquezblog.`yelparchives`;

CREATE TABLE IF NOT EXISTS cvazquezblog.`yelparchives` (
	`id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`userId` MEDIUMINT UNSIGNED NOT NULL,
	FOREIGN KEY (userId) REFERENCES users(id),
	`pageNumber` SMALLINT UNSIGNED NOT NULL,

	UNIQUE KEY (userId, pageNumber),

	`content` MEDIUMTEXT NOT NULL,

	`createdAt` DATETIME NULL DEFAULT NULL,
	`createdBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`updatedAt` DATETIME NULL DEFAULT NULL,
	`updatedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`deletedAt` DATETIME NULL DEFAULT NULL,
	`deletedBy` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
	`timestampAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP


) COMMENT = "Raw dump of review pages"
  ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;


grant insert, update on cvazquezblog.yelparchives to 'railo'@'localhost';